#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define TRANSITION_TIME 1
#define OBSTACLE_FREQUENCY 0.003

#define UPPER_GAP 0.70
//#define GAP 2
#define LOWER_GAP 0.20

#define CAR_COLLITION_BITMASK 0x000001
#define OBSTACLE_COLLITION_BITMASK 0x000002

#endif // __DEFINITIONS_H__
